import PDFDocument from 'pdfkit';
import { Response } from 'express';

export const generatePrescriptionPDF = (
  res: Response,
  data: {
    patientName: string;
    doctorName: string;
    specialty: string;
    date: string;
    medications: Array<{ name: string; dosage: string; frequency: string; duration: string }>;
    instructions?: string;
  }
): void => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="prescription-${Date.now()}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fontSize(20).fillColor('#00D4FF').text('MediSync', { align: 'center' });
  doc.fontSize(10).fillColor('#5A7A9B').text('Medical Prescription', { align: 'center' });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#00D4FF').stroke();
  doc.moveDown();

  // Doctor info
  doc.fontSize(12).fillColor('#333').text(`Dr. ${data.doctorName}`, { continued: true });
  doc.fillColor('#666').text(` — ${data.specialty}`, { align: 'right' });
  doc.text(`Date: ${data.date}`, { align: 'right' });
  doc.moveDown();

  // Patient
  doc.fontSize(11).fillColor('#333').text(`Patient: ${data.patientName}`);
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ccc').stroke();
  doc.moveDown();

  // Medications
  doc.fontSize(13).fillColor('#00D4FF').text('Medications');
  doc.moveDown(0.5);
  data.medications.forEach((med, i) => {
    doc.fontSize(11).fillColor('#333').text(`${i + 1}. ${med.name}`);
    doc.fontSize(10).fillColor('#666')
      .text(`   Dosage: ${med.dosage}  |  Frequency: ${med.frequency}  |  Duration: ${med.duration}`);
    doc.moveDown(0.3);
  });

  if (data.instructions) {
    doc.moveDown();
    doc.fontSize(11).fillColor('#333').text('Instructions:');
    doc.fontSize(10).fillColor('#666').text(data.instructions);
  }

  // Footer
  doc.moveDown(2);
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ccc').stroke();
  doc.fontSize(9).fillColor('#999').text('This prescription was generated by MediSync. Keep for your records.', { align: 'center' });

  doc.end();
};

export const generateInvoicePDF = (
  res: Response,
  data: {
    invoiceNumber: string;
    patientName: string;
    doctorName: string;
    date: string;
    acts: Array<{ description: string; amount: number }>;
    total: number;
    status: string;
  }
): void => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="invoice-${data.invoiceNumber}.pdf"`);
  doc.pipe(res);

  doc.fontSize(20).fillColor('#00D4FF').text('MediSync — Invoice', { align: 'center' });
  doc.moveDown();
  doc.fontSize(10).fillColor('#666').text(`Invoice #: ${data.invoiceNumber}`, { align: 'right' });
  doc.text(`Date: ${data.date}`, { align: 'right' });
  doc.text(`Status: ${data.status}`, { align: 'right' });
  doc.moveDown();

  doc.fontSize(11).fillColor('#333').text(`Patient: ${data.patientName}`);
  doc.text(`Doctor: Dr. ${data.doctorName}`);
  doc.moveDown();

  // Table header
  doc.fillColor('#00D4FF').text('Description', 50, doc.y, { continued: true });
  doc.text('Amount', { align: 'right' });
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#00D4FF').stroke();
  doc.moveDown(0.5);

  data.acts.forEach(act => {
    doc.fillColor('#333').fontSize(10).text(act.description, 50, doc.y, { continued: true });
    doc.text(`€${act.amount.toFixed(2)}`, { align: 'right' });
  });

  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ccc').stroke();
  doc.fontSize(12).fillColor('#333').text('Total:', 50, doc.y + 5, { continued: true });
  doc.fillColor('#00D4FF').text(`€${data.total.toFixed(2)}`, { align: 'right' });

  doc.end();
};
